
GET http://localhost:8080
Content-Type: application/json

###
GET http://localhost:8080/health
Content-Type: application/json

###
POST http://localhost:8080/api/auth/local/login
Content-Type: application/json

{
   "email":"ramavathshiva6300@gmail.com",
   "password":"12345678"
}

###
GET http://localhost:8080/api/auth/auth/auth-check
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRoSWQiOiI2OWEyY2MxODMxZGE4ZDE4MTNlZWJjODYiLCJ0b2tlblZlcnNpb24iOjIsInR5cGUiOiJhY2Nlc3MiLCJpYXQiOjE3Nzc3Nzk1NTksImV4cCI6MTc3Nzc4MDQ1OX0.iCOHuhFSoYp6McXN14MF21BcXqBo5Jz0Sh8VUOr1ZipV7HyFNCqvXMMRxoCkvshQUJIaC6BI7gNScVzQxBg5ybHu1OuZ_6kPxHs5oZIl4_GjAIhw-rpS4N5KAkfwis-CgqQNo2OEv8ql89yGbankNRJvuWm6oDgPoD3Pvkf3eHCRXoRdfecQa8VNrh7883QLjBDHQjXpEEdfUIm_6dLqXvxMteI1DXcI02lFUmPoIpwEb1is9_03bddALzUbz2iV_HaiG-7ykCTwl3m0iZYfh5XbUL-X3if-9D2YLafi_0k680qtUdT5tE1OBDQhfQiJrTXRVs-bHnau9G8DFjUo0w
###
GET http://localhost:8080/api/auth/auth/refresh-token
Content-Type: application/json
Set-Cookie: refreshToken=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRoSWQiOiI2OWEyY2MxODMxZGE4ZDE4MTNlZWJjODYiLCJ0b2tlblZlcnNpb24iOjIsInR5cGUiOiJyZWZyZXNoIiwiaWF0IjoxNzc3NzIyMjgyLCJleHAiOjE3NzgzMjcwODJ9.clJbj8oX8LJ_FDOI1WMoLteUl-kSYY_w1PNLi30Uus7TVKzhlaQCD19jLRAy8DHaFm16ujFuASbuiZC8bN31NntDvkyPdi5WzcILXaAEqaucHznjPG-knAvqD4LSUyJ-xsWy0h_ZiHjArm2QxGE8cChYdasTsj9Wx80-l3rtIID_nra7uG1wztbFpo6t_i8sAqVJN_HJzPaXWiMTh0YBiDOw8xHPgdwL7fDkqvYB0Pky5rC4g2vAJgCpLl9Kn1zYfgLfW_xBSqML9QG6a2RqMw8zufOAOgsasGwnAu_5mPQ7oAjziJZiFQ8zWc3y4SgkCmOYodFh2FfHy41YCbHXFw; Max-Age=86400; Path=/; Expires=Sun, 03 May 2026 11:44:42 GMT; HttpOnly; SameSite=Lax

###
GET http://localhost:8080/api/user/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRoSWQiOiI2OWEyY2MxODMxZGE4ZDE4MTNlZWJjODYiLCJ0b2tlblZlcnNpb24iOjIsInR5cGUiOiJhY2Nlc3MiLCJpYXQiOjE3Nzc3Nzk1NTksImV4cCI6MTc3Nzc4MDQ1OX0.iCOHuhFSoYp6McXN14MF21BcXqBo5Jz0Sh8VUOr1ZipV7HyFNCqvXMMRxoCkvshQUJIaC6BI7gNScVzQxBg5ybHu1OuZ_6kPxHs5oZIl4_GjAIhw-rpS4N5KAkfwis-CgqQNo2OEv8ql89yGbankNRJvuWm6oDgPoD3Pvkf3eHCRXoRdfecQa8VNrh7883QLjBDHQjXpEEdfUIm_6dLqXvxMteI1DXcI02lFUmPoIpwEb1is9_03bddALzUbz2iV_HaiG-7ykCTwl3m0iZYfh5XbUL-X3if-9D2YLafi_0k680qtUdT5tE1OBDQhfQiJrTXRVs-bHnau9G8DFjUo0w

###
POST http://localhost:8080/api/auth/local/register
Content-Type: application/json

{
   "email":"ramavathshiva6333@gmail.com",
   "password":"12345678",
   "userName":"shiva ram"
}