
GET http://localhost:8081
Content-Type: application/json

###
GET http://localhost:8081/health
Content-Type: application/json


###
POST http://localhost:8081/api/local/login
Content-Type: application/json

{
   "email":"ramavathshiva6300@gmail.com",
   "password":"12345678"
}

###
POST http://localhost:8081/api/local/register
Content-Type: application/json

{
   "email":"ramavathshiva3433@gmail.com",
   "password":"12345678",
   "userName":"shiva ram"
}

###
GET http://localhost:8081/api/auth/auth-check
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlblZlcnNpb24iOjIsInR5cGUiOiJhY2Nlc3MiLCJpYXQiOjE3Nzc3ODc5OTcsImV4cCI6MTc3Nzc4ODg5N30.AGFZBKWH75MHJXSVFsid16wX2HYBgnghOmsVwKvLrMmLZnQOyjWly2-9tdLaXCZY1STWEv-_oqnQ9GeZUGbQv2LdyeL5x-pR7aFAm7aNqBgMKWXxHfd83DZogSo-zXxZ6LRiKNQRG2llzDL-HFwBqMtwYvYAVTZ_6VMJB_e4Dm4lE3az9T1NcxG0Jo0QdCuy0tw2NsKVbRPTLTcarVt4_yi2mprG-ztWl0ZF1yhHDTtjU3QFNhA2eoZPAoN8ZuW0d8CfCmMpizsVlyCsTY8jCW2reMWBnX_sFeEymA2rv4NcCJLTP_scsfHfXneFY4ZX7dYT-4a0dKhB8tKQ5Xj7Yw

###
GET http://localhost:8081/api/auth/refresh-token
Content-Type: application/json
Set-Cookie: refreshToken=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRoSWQiOiI2OWEyY2MxODMxZGE4ZDE4MTNlZWJjODYiLCJ0b2tlblZlcnNpb24iOjIsInR5cGUiOiJyZWZyZXNoIiwiaWF0IjoxNzc3NzE4OTk0LCJleHAiOjE3NzgzMjM3OTR9.hp7D4Z0v5iDykoueKWPdxjlvpWeO3kGeHjpzG8lGHNDGfmqR3C5h20wPNaLNIbDjXifnif9SL40Sp6X9m72MsCZWXLR_rKdAHnaOyE3_ovIWIGJ1TgWDyyIqib7847PeRvMAPNJRWOdA45hLas2d3e8GZaDpgki0kCF7Dr_JWKTTw-Z_gBvCKfxcW_koWrq8O21VPROPc2IySkLu61kVXssK2_PieeR-TvMGH8a5IsMnrdCgMkkn-ae_PUB8uukVWIwfb1QIjofS7lFabZLayyo84pVSEt-dQKKxT5FoE3DMVazoDXCNObe1iGWX6AWH_mkBwxIOh5GM7-GQA7PwCA; Max-Age=86400; Path=/; Expires=Sun, 03 May 2026 10:49:54 GMT; HttpOnly; SameSite=Lax

###
POST http://localhost:8081/api/password/forgot-password
Content-Type: application/json

{
   "email":"ramavathshiva6300@gmail.com"
}

###
POST http://localhost:8081/api/password/verify-otp
Content-Type: application/json

{
   "email":"ramavathshiva6300@gmail.com",
   "otp":"123456"
}

###
POST http://localhost:8081/api/password/reset-password
Content-Type: application/json

{
   "email":"ramavathshiva6300@gmail.com",
   "otp":"123456",
   "password":"12345678"
}
