services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    ports:
      - "5173:5173"

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    ports:
      - "8080:8080"

  worker:
    build:
      context: ./server
      dockerfile: Dockerfile.worker
    container_name: worker

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"