GET http://localhost:8083/health
Content-Type: application/json

###
POST http://localhost:8083/api/workflow
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OWY2ZTRmZDBmZDg2NjAxOGVlNmRmMjkiLCJ0b2tlblZlcnNpb24iOjAsInR5cGUiOiJhY2Nlc3MiLCJpYXQiOjE3Nzc3ODgxNTcsImV4cCI6MTc3Nzc4OTA1N30.aRcUHdtjBdd8KXhPE693nvUyqrkm-PvEP6NE2yRQsLEll7u6cA_4r882yzw7uEaCPgkobhlzyscTBbuuJ8czY56HAXYq7fe7Kzi1ter6aZRmNkCsDpAkD9tcYItn9f_f-Yvp7RjT49jbjU2KNxMwciefNnkeXDjsIF_dRLK_XMM5QJni4kUZ052UNn3MUDhIKz4iLdCXDRRpx-8JbJo88MqcfBjOGdYq0Nnj-M1wr8QphL5xcoq7DRDSs-9j7cPcYf82NuH99NfAUq5LH0or8ZZ2YfW5GCM1c2JbkDjg3mxDZ1PVZnbkkN9mHzvo0bzWRo2ABRodJxtuc729tp__eQ




###
GET http://localhost:8083/api/workflow
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OWY2ZTRmZDBmZDg2NjAxOGVlNmRmMjkiLCJ0b2tlblZlcnNpb24iOjAsInR5cGUiOiJhY2Nlc3MiLCJpYXQiOjE3Nzc3ODgxNTcsImV4cCI6MTc3Nzc4OTA1N30.aRcUHdtjBdd8KXhPE693nvUyqrkm-PvEP6NE2yRQsLEll7u6cA_4r882yzw7uEaCPgkobhlzyscTBbuuJ8czY56HAXYq7fe7Kzi1ter6aZRmNkCsDpAkD9tcYItn9f_f-Yvp7RjT49jbjU2KNxMwciefNnkeXDjsIF_dRLK_XMM5QJni4kUZ052UNn3MUDhIKz4iLdCXDRRpx-8JbJo88MqcfBjOGdYq0Nnj-M1wr8QphL5xcoq7DRDSs-9j7cPcYf82NuH99NfAUq5LH0or8ZZ2YfW5GCM1c2JbkDjg3mxDZ1PVZnbkkN9mHzvo0bzWRo2ABRodJxtuc729tp__eQ





###
GET http://localhost:8083/api/workflow/69f6e5a29623ee3e89863d14
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlblZlcnNpb24iOjIsInR5cGUiOiJhY2Nlc3MiLCJpYXQiOjE3Nzc3ODc5OTcsImV4cCI6MTc3Nzc4ODg5N30.AGFZBKWH75MHJXSVFsid16wX2HYBgnghOmsVwKvLrMmLZnQOyjWly2-9tdLaXCZY1STWEv-_oqnQ9GeZUGbQv2LdyeL5x-pR7aFAm7aNqBgMKWXxHfd83DZogSo-zXxZ6LRiKNQRG2llzDL-HFwBqMtwYvYAVTZ_6VMJB_e4Dm4lE3az9T1NcxG0Jo0QdCuy0tw2NsKVbRPTLTcarVt4_yi2mprG-ztWl0ZF1yhHDTtjU3QFNhA2eoZPAoN8ZuW0d8CfCmMpizsVlyCsTY8jCW2reMWBnX_sFeEymA2rv4NcCJLTP_scsfHfXneFY4ZX7dYT-4a0dKhB8tKQ5Xj7Yw