export const WORKFLOW_EVENTS = {
  NODE_ADD: "node:add",
  NODES_ADD: "nodes:add",
  NODE_UPDATE: "node:update",
  NODE_REMOVE: "node:remove",
  NODES_REMOVE: "nodes:remove",
  NODE_GET: "node:get",
  NODES_GET: "nodes:get",

  EDGE_ADD: "edge:add",
  EDGES_ADD: "edges:add",
  EDGE_UPDATE: "edge:update",
  EDGE_REMOVE: "edge:remove",
  EDGES_REMOVE: "edges:remove",
  EDGE_GET: "edge:get",
  EDGES_GET: "edges:get",

  FACULTY_ADD: "faculty:add",
  FACULTIES_ADD: "faculties:add",
  FACULTY_UPDATE: "faculty:update",
  FACULTY_REMOVE: "faculty:remove",
  FACULTIES_REMOVE: "faculties:remove",
  FACULTY_GET: "faculty:get",
  FACULTIES_GET: "faculties:get",

  SUBJECT_ADD: "subject:add",
  SUBJECTS_ADD: "subjects:add",
  SUBJECT_UPDATE: "subject:update",
  SUBJECT_REMOVE: "subject:remove",
  SUBJECTS_REMOVE: "subjects:remove",
  SUBJECT_GET: "subject:get",
  SUBJECTS_GET: "subjects:get",

  ROOM_ADD: "room:add",
  ROOMS_ADD: "rooms:add",
  ROOM_UPDATE: "room:update",
  ROOM_REMOVE: "room:remove",
  ROOMS_REMOVE: "rooms:remove",
  ROOM_GET: "room:get",
  ROOMS_GET: "rooms:get",

  MESSAGE_SEND: "message:send",
  MESSAGE_RESPONSE: "message:response",
};
